
#include "Custom_Exception.h"
#include "Insufficient_Money_Exception.h"
#include "Full_Team_Exception.h"
#include "Friendly_Fire_Exception.h"
#include "Dead_Player_Exception.h"
#include "Dead_Buyer_Exception.h"
#include "Dead_Attacker_Exception.h"
#include "Dead_Attacked_Exception.h"
#include "Invalid_Attribute_Exception.h"
#include "Invalid_UserName_Exception.h"
#include "Invalid_GunType_Exception.h"
#include "Invalid_GunCategory_Exception.h"
#include "Duplicate_Attribute_Exception.h"
#include "Duplicate_UserName_Exception.h"
#include "Duplicate_WeaponType_Exception.h"
#include "Duplicate_Heavy_Gun_Exception.h"
#include "Duplicate_Pistol_Exception.h"
